packages:
  - packages/ai-chat-bootstrap
  - packages/ai-chat-bootstrap-demo
  - packages/ai-chat-bootstrap-docs
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
